apiVersion: apps/v1
kind: Deployment
metadata:
  name: anisug-deployment
  labels:
    app: anisug
  namespace: anisug
spec:
  replicas: 2
  selector:
    matchLabels:
      app: anisug
  template:
    metadata:
      labels:
        app: anisug
    spec:
      containers:
      - name: anisug
        image: docker.io/joy1998/animesuggestionapp:v1
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: anisug-service
  namespace: anisug
spec:
  selector:
    app: anisug
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: NodePort